/*
    Typings for Teardown Lua API 1.5
    by blackshibe, written 26/06/2024
*/

// UiMakeInteractive
// UiPush
// UiPop
// UiWidth
// UiHeight
// UiCenter
// UiMiddle
// UiColor
// UiColorFilter
// UiResetColor
// UiTranslate
// UiRotate
// UiScale
// UiGetScale
// UiClipRect
// UiWindow
// UiGetCurrentWindow
// UiIsInCurrentWindow
// UiIsRectFullyClipped
// UiIsInClipRegion
// UiIsFullyClipped
// UiSafeMargins
// UiCanvasSize
// UiAlign
// UiTextAlignment
// UiModalBegin
// UiModalEnd
// UiDisableInput
// UiEnableInput
// UiReceivesInput
// UiGetMousePos
// UiGetCanvasMousePos
// UiIsMouseInRect
// UiWorldToPixel
// UiPixelToWorld
// UiGetCursorPos
// UiBlur
// UiFont
// UiFontHeight
// UiText
// UiTextUniformHeight
// UiGetTextSize
// UiMeasureText
// UiGetSymbolsCount
// UiTextSymbolsSub
// UiWordWrap
// UiTextLineSpacing
// UiTextOutline
// UiTextShadow
// UiRect
// UiRectOutline
// UiRoundedRect
// UiRoundedRectOutline
// UiCircle
// UiCircleOutline
// UiImage
// UiUnloadImage
// UiHasImage
// UiGetImageSize
// UiImageBox
// UiSound
// UiSoundLoop
// UiMute
// UiButtonImageBox
// UiButtonHoverColor
// UiButtonPressColor
// UiButtonPressDist
// UiButtonTextHandling
// UiTextButton
// UiImageButton
// UiBlankButton
// UiSlider
// UiSliderHoverColorFilter
// UiSliderThumbSize
// UiGetScreen
// UiNavComponent
// UiIgnoreNavigation
// UiResetNavigation
// UiNavSkipUpdate
// UiIsComponentInFocus
// UiNavGroupBegin
// UiNavGroupEnd
// UiNavGroupSize
// UiForceFocus
// UiFocusedComponentId
// UiFocusedComponentRect
// UiGetItemSize
// UiAutoTranslate
// UiBeginFrame
// UiResetFrame
// UiFrameOccupy
// UiEndFrame
// UiFrameSkipItem
// UiGetFrameNo
// UiGetLanguage
// UiSetCursorState
